name: socket_io_common_client
description: Dartlang port of socket.io-client, Support VM(Flutter, cmd, server) and web front-end
version: 0.10.0+1
author: bixiaopeng <bixiaopeng2007@gmail.com>
homepage: https://github.com/moshoujingli/socket.io-client-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: ^1.0.0
  socket_io_common: ^1.0.0

dev_dependencies:
  test:
  build_runner:
  build_web_compilers:
  socket_io: any
