name: socket_io_common_client
description: Dartlang port of socket.io-client
version: 0.9.6
author: bixiaopeng <bixiaopeng2007@gmail.com>
homepage: https://github.com/moshoujingli/socket.io-client-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  socket_io_common: ^0.9.0+1

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
  socket_io: any

  
